### ISSUE TITLE
Создание банковского счёта (админка): null null вместо Фамилии и Имени пользователя в сообщении об успешной операции

### ISSUE THREAD

**Issue by rimsky90** [martosvadim/ibs#10]
http://gyazo.com/46034bd0c9302ff271e93c823f601efe - Имя и Фамилия должны быть вместо null null (в данном примере эти данные заполнены в профиле пользователя)

**Comment by maxyeg** [comment]
Fixed

**Comment by rimsky90** [comment]
Passed
