### ISSUE TITLE
Ошибка при попытке пополнить банковский счёт

### ISSUE THREAD

**Issue by rimsky90** [martosvadim/ibs#13]
1) Заходим в админку
2) Нажимаем "Пополнить счёт"
3) Вводим корректный id
Результат: получаем ворнинг: http://gyazo.com/5d5e74b8ff2d7f6da352f84267a12435

**Comment by maxyeg** [comment]
Fixed

**Comment by rimsky90** [comment]
still reproducible

**Comment by rimsky90** [comment]
not reproducible anymore
