### ISSUE TITLE
Ошибка при отправлении заявки на карту новым юзером

### ISSUE THREAD

**Issue by rimsky90** [martosvadim/ibs#17]
1) Регистрируемся
2) Не заполняя данных о пользователе, отправляем заявку на карту
Резалт: http://gyazo.com/5176f7af46f3f72f0cb3411c543aa47a
Ожидаемый: Мессага "Пожалуйста, заполните информацию о себе в Настройках"

**Comment by maxyeg** [comment]
Fixed

**Comment by rimsky90** [comment]
passed
