### ISSUE TITLE
Форма Пополнение Счёта: Можно пополнить счёт на отрицательное значение

### ISSUE THREAD

**Issue by rimsky90** [martosvadim/ibs#5]
1) Заходим в админку и нажимаем "Пополнение счёта". 
2) Вводим номер счёта и нажимаем "Проверить"
3) Нажимаем "Далее"
4) На форме "Пополнение счёта" вводим отрицательное значение и жмём "Пополнить"
Результат: получаем сообшение об успешном пополнении счёта
http://gyazo.com/1402a62b9f3abe344fa166b84c8a3b9a

**Comment by maxyeg** [comment]
Fixed

**Comment by rimsky90** [comment]
passed
