### ISSUE TITLE
Заявка на создание карт счёта: нет валидационных сообщений (ворнингов)

### ISSUE THREAD

**Issue by rimsky90** [martosvadim/ibs#7]
Если мы не выбрали номер счёта и нажали "Отправить", то появляется мессага "Номер банковского счёта не заполнен."
Если же выбран номер счёта, но не выбраны Тип карты и / или Валюта, мы жмём "Отправить", то не получаем вообще никаких сообщений
http://gyazo.com/51b9ecc152e901c980189b412de075d4

**Comment by maxyeg** [comment]
Fixed

**Comment by rimsky90** [comment]
passed
